# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: NotNot
baseline: The Brain Breaker
email: contact@notnot.fr
altshift_email: contact@altshift.fr
description: > # this means to ignore newlines until "baseurl:"
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean quis lobortis elit. Maecenas faucibus magna sed nisi dapibus, sit amet faucibus neque volutpat. Mauris ac sem a felis volutpat posuere a imperdiet mauris. Sed ipsum quam, viverra ut sagittis eget, tincidunt nec leo. Duis id pretium turpis. Suspendisse sollicitudin quis est eget rutrum. Phasellus nec enim a dolor feugiat semper. Sed varius vulputate vehicula. Fusce eu ante iaculis, condimentum libero sit amet, finibus sem. Maecenas tincidunt sagittis libero, eu bibendum augue vehicula at. Sed faucibus dictum mattis. Mauris at felis ac eros pharetra pretium.
baseurl: "/notnot-website" # the subpath of your site, e.g. /blog
url: "https://altshift.github.io" # the base hostname & protocol for your site
twitter_username: notnot_game
facebook_username: notnot
github_username:  altshift
repository: notnot-website/atlshift.github.io
# Build settings
markdown: kramdown
sass:
    sass_dir: ./css