# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Crying Suns
share_title_end: Tactical space rogue-lite
baseline: When FTL meets Foundation
email: idaho@ncryingsuns.com
altshift_email: contact@altshift.fr
description: > # this means to ignore newlines until "baseurl:"
  CRYING SUNS is a rogue-lite and tactical game where you explore a dying galaxy as a space fleet commander. As a deep story-driven game experience, each successful run will uncover a part of the underlying truth about the fall of the galactic Empire.
share_description: >
  CRYING SUNS is a rogue-lite and tactical game where you explore a dying galaxy as a space fleet commander. As a deep story-driven game experience, each successful run will uncover a part of the underlying truth about the fall of the galactic Empire.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://altshift.github.io" # the base hostname & protocol for your site
share_url: "www.cryingsuns.com"
twitter_username: cryingsuns
facebook_username: facebook.com/cryingsuns
facebook_text: Crying Suns
github_username:  altshift
entreprise: Altshift
commingsoon: COMING SOON

repository: cryningsuns-website/atlshift.github.io
# Build settings
markdown: kramdown
sass:
    sass_dir: ./css
